### ISSUE TITLE
MoonShine v3.x support

### ISSUE THREAD

**Issue by shevl-dev** [lee-to/laravel-seo-by-url#13]
Я бы, возможно, попробовал обновить пакет, хотя пока даже не представляю, как это сделать, пока даже свой текущий проект на 3й мун не перевёл.
И я пока не совсем понимаю как в таких случаях поступать? Нужно создать отдельную ветку v3.x потом смержить её с мастером и создать релиз? А последний на данным момент релиз будет последним поддерживающим moonshine v2.x? Как тогда сделать, чтобы параллельно поддерживать ветки для 2 и 3 муншайна?
Но, я так понимаю, самостоятельно зарелизить я не смогу.

**Comment by lee-to** [comment]
Текущую нужно будет переименовать в 1.x а для 3 версии создать 2.х
Сам пакет не обязан своей версией подстраиваться по муншайн

Для поддержки нужно просто обновить ресурсы

**Comment by shevl-dev** [comment]
> Сам пакет не обязан своей версией подстраиваться по муншайн

Да это понятно, просто для наглядности, ранее при обновлении для совместимости со 2м муном создавалась ветка с названием v2, она собственно и осталась )
Получается будет путаница если сейчас создать ветку v2.x, старую ветку стоит удалить.

**Comment by lee-to** [comment]
> > Сам пакет не обязан своей версией подстраиваться по муншайн
> 
> 
> 
> Да это понятно, просто для наглядности, ранее при обновлении для совместимости со 2м муном создавалась ветка с названием v2, она собственно и осталась )
> 
> Получается будет путаница если сейчас создать ветку v2.x, старую ветку стоит удалить.

Возможно потребуется навести порядок

**Comment by DissNik** [comment]
я что-то не встречал чтоб пакет по релизам соответствовал , у каждого своя история развития

**Comment by shevl-dev** [comment]
> я что-то не встречал чтоб пакет по релизам соответствовал , у каждого своя история развития

Да я и не утверждал обратного ))
Я просто сказал, что ранее в пакете была создана ветка v2, когда выполнялось обновление для совместимости со 2й версией муншайна.

**Comment by shevl-dev** [comment]
> Для поддержки нужно просто обновить ресурсы

Слушай, я начал обновлять пакет, пришлось переписать код команды, которая публикует ресурс, в итоге решил удалить старые стабы для 1й и 2й версии муншайна, т.к. всё равно нарушается совместимость с этими версиями.
НО, потом подумал, может лучше оставить старую команду и старые стабы, а для 3й версии муншайна написать отдельную команду?

Обновление с переписанной командой и с единственным стабом для 3й версии муншайна уже готово, готов запушить, но решил уточнить.

**Comment by shevelev-anatoliy** [comment]
Как минимум
