### ISSUE TITLE
Получил ошибку с Leeto\Seo\SeoManager::cachedByUrl() Return value must be of type

### ISSUE THREAD

**Issue by saydum** [lee-to/laravel-seo-by-url#4]
Привет!

Получил вот такю ошибку после установки и настройки memcached

Leeto\Seo\SeoManager::cachedByUrl(): Return value must be of type Illuminate\Database\Eloquent\Model|Leeto\Seo\Models\Seo|null, Illuminate\Database\Eloquent\Collection returned (View: /var/www/rodipriroda.com/resources/views/layouts/web.blade.php) (View: /var/www/rodipriroda.com/resources/views/layouts/web.blade.php)

- Laravel 10.10
- Php 8.2

**Comment by lee-to** [comment]
Привет! Странно что там коллекция! Пришлите дамп того что отдает метод

**Comment by saydum** [comment]
Не могу повторно произвести эту ошибку
- Убрал пока memcached
- очистил кеш view
Больше не выводится

**Comment by saydum** [comment]
Скорее всего ошибка возникла при конфликте миграции.
