### ISSUE TITLE
Заменить поле TinyMce на Markdown

### ISSUE THREAD

**Issue by shevl-dev** [lee-to/laravel-seo-by-url#6]
Раз уж в 3й версии TinyMce уйдёт в отдельный пакет.

Могу сам сделать на выходных, пишу чтобы получить одобрение ))

**Comment by shevl-dev** [comment]
Ещё предлагаю по умолчанию скрыть поле 'Text' на индексной странице, текст может быть шибко длинным, а кому надо сам уберёт `hideOnIndex()`

**Comment by lee-to** [comment]
Это будет breaking change, давай это сделаем после релиза 3.0
Насчет indexFields добро
